theme: minima

# Name of your site (displayed in the header)
name: Name
# Short bio or description (displayed in the header)
description: Developer from Somewhere
author: Author

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.google.de/url?sa=i&url=https%3A%2F%2Fvectorportal.com%2Fvector%2Fblack-man-avatar%2F35840&psig=AOvVaw3zhCxc9xi2eetON-jZrh3s&ust=1678212338658000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCKjJv6zyx_0CFQAAAAAdAAAAABAE
